/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M18
 * Generated at: 2017-04-21 05:48:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import codes.*;
import java.text.SimpleDateFormat;

public final class checkout1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 static int hitsCount=0; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("codes");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <meta name=\"googlebot\" content=\"index,follow,snippet,archive\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"Obaju e-commerce template\">\r\n");
      out.write("    <meta name=\"author\" content=\"Ondrej Svestka | ondrejsvestka.cz\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>\r\n");
      out.write("          Electric Smiling\r\n");
      out.write("    </title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("    <!-- styles -->\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.theme.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- theme stylesheet -->\r\n");
      out.write("    <link href=\"css/style.default.css\" rel=\"stylesheet\" id=\"theme-stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- your stylesheet with modifications -->\r\n");
      out.write("    <link href=\"css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // WRITE THE VALIDATION SCRIPT IN THE HEAD TAG.\r\n");
      out.write("    function isNumber(evt) {\r\n");
      out.write("        var iKeyCode = (evt.which) ? evt.which : evt.keyCode\r\n");
      out.write("        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))\r\n");
      out.write("            return false;\r\n");
      out.write("\r\n");
      out.write("        return true;\r\n");
      out.write("    } \r\n");
      out.write("    function isNumber1(evt) {\r\n");
      out.write("        var iKeyCode = (evt.which) ? evt.which : evt.keyCode\r\n");
      out.write("        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))\r\n");
      out.write("            return false;\r\n");
      out.write("\r\n");
      out.write("        return true;\r\n");
      out.write("    } \r\n");
      out.write("    \r\n");
      out.write("    function ValidateNo() {\r\n");
      out.write("        var phoneNo = document.getElementById('tbNumbers');\r\n");
      out.write("\r\n");
      out.write("    if (phoneNo.value == \"\" || phoneNo.value == null) {\r\n");
      out.write("            alert(\"Please enter your Mobile No.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (phoneNo.value.length < 10 || phoneNo.value.length > 10) {\r\n");
      out.write("            alert(\"Mobile No. is not valid, Please Enter 10 Digit Mobile No.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        return true;\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

Connection con = DBConnection.getDBConnection();

String uname = UserCredentials.getUsername();
String email = UserCredentials.getEmailId();
int userid = UserCredentials.getUserid();
String url = request.getRequestURL().toString();
SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
java.util.Date date=new java.util.Date();  
String d=dateFormat.format(date);


try{
	


if (hitsCount == 0) 
{
	hitsCount++;
PreparedStatement ps=con.prepareStatement("insert into  clicks(url,hits,date) values(?,?,?)");
		    ps.setString(1,url);
		    ps.setInt(2,hitsCount);
		   
		    ps.setString(3,d);	
		    int i=ps.executeUpdate();

}
else
{

hitsCount++;

	PreparedStatement ps3=con.prepareStatement("update clicks set hits='"+hitsCount+"' where date='"+d+"' and url='"+url+"'");
	  
	  
	  int j=ps3.executeUpdate();


}
}
catch(Exception e){
	System.out.print(e);
}


		
  
    
	
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- *** TOPBAR ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("    <div id=\"top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"col-md-6 offer\" data-animate=\"fadeInDown\">\r\n");
      out.write("<!--                 <a href=\"#\" class=\"btn btn-success btn-sm\" data-animate-hover=\"shake\">Offer of the day</a>  <a href=\"#\">Get flat 35% off on orders over $50!</a>\r\n");
      out.write(" -->            </div>\r\n");
      out.write("            <div class=\"col-md-6\" data-animate=\"fadeInDown\">\r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                \r\n");
      out.write("                ");
if(userid>=1){
                	
                	
                	
      out.write("\r\n");
      out.write("                \t<li ><a  href=\"#\"><i class=\"fa fa-user\"></i>");
      out.print(uname );
      out.write(" </a>\r\n");
      out.write("                \t<li ><a  href=\"logout.jsp\"><i class=\"fa fa-user\"></i>Logout </a>\r\n");
      out.write("                \t");

                }
                else{
                	
      out.write("\r\n");
      out.write("                \t<li><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"register.jsp\">Register</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                \t");

                	
                }
                
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <li><a href=\"contact.html\">Contact</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"Login\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                        <h4 class=\"modal-title\" id=\"Login\">Customer login</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <form action=\"Login\" method=\"post\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" name=\"username\" class=\"form-control\" id=\"email-modal\" placeholder=\"email\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"password\" name=\"password\" class=\"form-control\" id=\"password-modal\" placeholder=\"password\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"text-center\">\r\n");
      out.write("                                <button class=\"btn btn-primary\"><i class=\"fa fa-sign-in\"></i> Log in</button>\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"text-center text-muted\">Not registered yet?</p>\r\n");
      out.write("                        <p class=\"text-center text-muted\"><a href=\"register.jsp\"><strong>Register now</strong></a>! It is easy and done in 1&nbsp;minute and gives you access to special discounts and much more!</p>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- *** TOP BAR END *** -->\r\n");
      out.write("\r\n");
      out.write("    <!-- *** NAVBAR ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar navbar-default yamm\" role=\"navigation\" id=\"navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("\r\n");
      out.write("                <a class=\"navbar-brand home\" href=\"index.html\" data-animate-hover=\"bounce\">\r\n");
      out.write("                    <img src=\"img/nameofwebsite.jpg\" style=\"width: 126px;height: 58px;\" alt=\"Obaju logo\" class=\"hidden-xs\">\r\n");
      out.write("                    <img src=\"img/logo-small.png\" alt=\"Obaju logo\" class=\"visible-xs\"><span class=\"sr-only\">Obaju - go to homepage</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"navbar-buttons\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navigation\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <i class=\"fa fa-align-justify\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#search\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle search</span>\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-collapse collapse\" id=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("                    <li ><a href=\"index.jsp\">Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"shop.jsp?p_type=1&brand=mobile\">Mobile</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=4&brand=Laptop\">Laptop</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=2&brand=Headphone\">Headphone</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=3&brand=Speaker\">Speaker</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=5&brand=Printer\">Printer</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                       <li ><a href=\"your_account.jsp\">Your Account</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!--/.nav-collapse -->\r\n");
      out.write("\r\n");
      out.write("           <div class=\"navbar-buttons\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"navbar-collapse collapse right\" id=\"basket-overview\">\r\n");
      out.write("                 ");

                    	String ucount = "";
                    String totalsum = "";
                    	PreparedStatement pscart = con.prepareStatement("SELECT COUNT(userid) AS usercount, SUM(total) AS totalsum FROM cart WHERE userid = " + userid + " GROUP BY userid");
                    	ResultSet rscart = pscart.executeQuery();
                    	if(rscart.next())
                    	{
                    		ucount = rscart.getInt("usercount")+"";
                    		totalsum = rscart.getInt("totalsum")+"";
                    	}
                    
      out.write("\r\n");
      out.write("                    <a href=\"basket.jsp?userid=");
      out.print(userid );
      out.write("\" class=\"btn btn-primary navbar-btn\"><i class=\"fa fa-shopping-cart\"></i><span class=\"hidden-sm\">");
      out.print(ucount );
      out.write(" items in cart</span></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.nav-collapse -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"navbar-collapse collapse right\" id=\"search-not-mobile\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn navbar-btn btn-primary\" data-toggle=\"collapse\" data-target=\"#search\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle search</span>\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse clearfix\" id=\"search\">\r\n");
      out.write("\r\n");
      out.write("                <form class=\"navbar-form\" method=\"post\" action=\"search.jsp\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"search\" placeholder=\"Search\">\r\n");
      out.write("                        <span class=\"input-group-btn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("\r\n");
      out.write("\t\t    </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.nav-collapse -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#navbar -->\r\n");
      out.write("\r\n");
      out.write("    <!-- *** NAVBAR END *** -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"all\">\r\n");
      out.write("\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <ul class=\"breadcrumb\">\r\n");
      out.write("                        <li><a href=\"#\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>Checkout - Address</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("<h1>Checkout</h1>\r\n");
      out.write("                            <ul class=\"nav nav-pills nav-justified\">\r\n");
      out.write("                                <li class=\"active\"><a href=\"#\"><i class=\"fa fa-map-marker\"></i><br>Address</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                               \r\n");
      out.write("                                <li class=\"disabled\"><a href=\"#\"><i class=\"fa fa-money\"></i><br>Payment Method</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                               \r\n");
      out.write("                            </ul>\r\n");
      out.write(" <div class=\"col-md-9\" id=\"checkout\">\r\n");
      out.write(" <div class=\"content\">\r\n");
      out.write(" <br><br><br><br>\r\n");
      out.write("<table style=\"width: 76% !important;\" class=\"table table-bordered table-striped\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>name</td>\r\n");
      out.write("\t<td>address</td>\r\n");
      out.write("\t<td>phone</td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td>Action</td>\r\n");
      out.write("</tr>\r\n");

PreparedStatement psa=con.prepareStatement("select * from  user_detail where userid='"+userid+"'");
ResultSet rsa=psa.executeQuery();
if(rsa.next()){
	
	
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>");
      out.print(rsa.getString("name") );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rsa.getString("address") );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rsa.getString("phone") );
      out.write("</td>\r\n");
      out.write("\t\t<td><a href=\"edit_address.jsp?uid=");
      out.print(userid);
      out.write("\">Update</a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</tr> </table>\r\n");
      out.write(" <a href=\"checkout3.jsp\" class=\"btn btn-default\"><i class=\"fa fa-chevron-left\"></i>Continue to Delivery Method</a>\r\n");
      out.write("\r\n");
      out.write("</div></div></div>\r\n");
      out.write("\r\n");
      out.write("\t");

	
	
}
else{
	
      out.write("\r\n");
      out.write("\t                <div class=\"col-md-9\" id=\"checkout\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <form method=\"post\" action=\"PlaceOrder\">\r\n");
      out.write("                            <h1>Checkout</h1>\r\n");
      out.write("                            <ul class=\"nav nav-pills nav-justified\">\r\n");
      out.write("                                <li class=\"active\"><a href=\"#\"><i class=\"fa fa-map-marker\"></i><br>Address</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                               \r\n");
      out.write("                                <li class=\"disabled\"><a href=\"#\"><i class=\"fa fa-money\"></i><br>Payment Method</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                               \r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"firstname\">country </label><br>\r\n");
      out.write("                                           \r\n");
      out.write("                                            <select   class=\"form-control\"  name=\"country\">\r\n");
      out.write("                                                   <option value=\"AX\">Åland Islands</option>\r\n");
      out.write("                                                    <option value=\"AF\">Afghanistan</option>\r\n");
      out.write("                                                    <option value=\"AL\">Albania</option>\r\n");
      out.write("                                                    <option value=\"DZ\">Algeria</option>\r\n");
      out.write("                                                    <option value=\"AD\">Andorra</option>\r\n");
      out.write("                                                    <option value=\"AO\">Angola</option>\r\n");
      out.write("                                                    <option value=\"AI\">Anguilla</option>\r\n");
      out.write("                                                    <option value=\"AQ\">Antarctica</option>\r\n");
      out.write("                                                    <option value=\"AG\">Antigua and Barbuda</option>\r\n");
      out.write("                                                    <option value=\"AR\">Argentina</option>\r\n");
      out.write("                                                    <option value=\"AM\">Armenia</option>\r\n");
      out.write("                                                    <option value=\"AW\">Aruba</option>\r\n");
      out.write("                                                    <option value=\"AU\">Australia</option>\r\n");
      out.write("                                                    <option value=\"AT\">Austria</option>\r\n");
      out.write("                                                    <option value=\"AZ\">Azerbaijan</option>\r\n");
      out.write("                                                    <option value=\"BS\">Bahamas</option>\r\n");
      out.write("                                                    <option value=\"BH\">Bahrain</option>\r\n");
      out.write("                                                    <option value=\"BD\">Bangladesh</option>\r\n");
      out.write("                                                    <option value=\"BB\">Barbados</option>\r\n");
      out.write("                                                    <option value=\"BY\">Belarus</option>\r\n");
      out.write("                                                    <option value=\"PW\">Belau</option>\r\n");
      out.write("                                                    <option value=\"BE\">Belgium</option>\r\n");
      out.write("                                                    <option value=\"BZ\">Belize</option>\r\n");
      out.write("                                                    <option value=\"BJ\">Benin</option>\r\n");
      out.write("                                                    <option value=\"BM\">Bermuda</option>\r\n");
      out.write("                                                    <option value=\"BT\">Bhutan</option>\r\n");
      out.write("                                                    <option value=\"BO\">Bolivia</option>\r\n");
      out.write("                                                    <option value=\"BQ\">Bonaire, Saint Eustatius and Saba</option>\r\n");
      out.write("                                                    <option value=\"BA\">Bosnia and Herzegovina</option>\r\n");
      out.write("                                                    <option value=\"BW\">Botswana</option>\r\n");
      out.write("                                                    <option value=\"BV\">Bouvet Island</option>\r\n");
      out.write("                                                    <option value=\"BR\">Brazil</option>\r\n");
      out.write("                                                    <option value=\"IO\">British Indian Ocean Territory</option>\r\n");
      out.write("                                                    <option value=\"VG\">British Virgin Islands</option>\r\n");
      out.write("                                                    <option value=\"BN\">Brunei</option>\r\n");
      out.write("                                                    <option value=\"BG\">Bulgaria</option>\r\n");
      out.write("                                                    <option value=\"BF\">Burkina Faso</option>\r\n");
      out.write("                                                    <option value=\"BI\">Burundi</option>\r\n");
      out.write("                                                    <option value=\"KH\">Cambodia</option>\r\n");
      out.write("                                                    <option value=\"CM\">Cameroon</option>\r\n");
      out.write("                                                    <option value=\"CA\">Canada</option>\r\n");
      out.write("                                                    <option value=\"CV\">Cape Verde</option>\r\n");
      out.write("                                                    <option value=\"KY\">Cayman Islands</option>\r\n");
      out.write("                                                    <option value=\"CF\">Central African Republic</option>\r\n");
      out.write("                                                    <option value=\"TD\">Chad</option>\r\n");
      out.write("                                                    <option value=\"CL\">Chile</option>\r\n");
      out.write("                                                    <option value=\"CN\">China</option>\r\n");
      out.write("                                                    <option value=\"CX\">Christmas Island</option>\r\n");
      out.write("                                                    <option value=\"CC\">Cocos (Keeling) Islands</option>\r\n");
      out.write("                                                    <option value=\"CO\">Colombia</option>\r\n");
      out.write("                                                    <option value=\"KM\">Comoros</option>\r\n");
      out.write("                                                    <option value=\"CG\">Congo (Brazzaville)</option>\r\n");
      out.write("                                                    <option value=\"CD\">Congo (Kinshasa)</option>\r\n");
      out.write("                                                    <option value=\"CK\">Cook Islands</option>\r\n");
      out.write("                                                    <option value=\"CR\">Costa Rica</option>\r\n");
      out.write("                                                    <option value=\"HR\">Croatia</option>\r\n");
      out.write("                                                    <option value=\"CU\">Cuba</option>\r\n");
      out.write("                                                    <option value=\"CW\">CuraÇao</option>\r\n");
      out.write("                                                    <option value=\"CY\">Cyprus</option>\r\n");
      out.write("                                                    <option value=\"CZ\">Czech Republic</option>\r\n");
      out.write("                                                    <option value=\"DK\">Denmark</option>\r\n");
      out.write("                                                    <option value=\"DJ\">Djibouti</option>\r\n");
      out.write("                                                    <option value=\"DM\">Dominica</option>\r\n");
      out.write("                                                    <option value=\"DO\">Dominican Republic</option>\r\n");
      out.write("                                                    <option value=\"EC\">Ecuador</option>\r\n");
      out.write("                                                    <option value=\"EG\">Egypt</option>\r\n");
      out.write("                                                    <option value=\"SV\">El Salvador</option>\r\n");
      out.write("                                                    <option value=\"GQ\">Equatorial Guinea</option>\r\n");
      out.write("                                                    <option value=\"ER\">Eritrea</option>\r\n");
      out.write("                                                    <option value=\"EE\">Estonia</option>\r\n");
      out.write("                                                    <option value=\"ET\">Ethiopia</option>\r\n");
      out.write("                                                    <option value=\"FK\">Falkland Islands</option>\r\n");
      out.write("                                                    <option value=\"FO\">Faroe Islands</option>\r\n");
      out.write("                                                    <option value=\"FJ\">Fiji</option>\r\n");
      out.write("                                                    <option value=\"FI\">Finland</option>\r\n");
      out.write("                                                    <option value=\"FR\">France</option>\r\n");
      out.write("                                                    <option value=\"GF\">French Guiana</option>\r\n");
      out.write("                                                    <option value=\"PF\">French Polynesia</option>\r\n");
      out.write("                                                    <option value=\"TF\">French Southern Territories</option>\r\n");
      out.write("                                                    <option value=\"GA\">Gabon</option>\r\n");
      out.write("                                                    <option value=\"GM\">Gambia</option>\r\n");
      out.write("                                                    <option value=\"GE\">Georgia</option>\r\n");
      out.write("                                                    <option value=\"DE\">Germany</option>\r\n");
      out.write("                                                    <option value=\"GH\">Ghana</option>\r\n");
      out.write("                                                    <option value=\"GI\">Gibraltar</option>\r\n");
      out.write("                                                    <option value=\"GR\">Greece</option>\r\n");
      out.write("                                                    <option value=\"GL\">Greenland</option>\r\n");
      out.write("                                                    <option value=\"GD\">Grenada</option>\r\n");
      out.write("                                                    <option value=\"GP\">Guadeloupe</option>\r\n");
      out.write("                                                    <option value=\"GT\">Guatemala</option>\r\n");
      out.write("                                                    <option value=\"GG\">Guernsey</option>\r\n");
      out.write("                                                    <option value=\"GN\">Guinea</option>\r\n");
      out.write("                                                    <option value=\"GW\">Guinea-Bissau</option>\r\n");
      out.write("                                                    <option value=\"GY\">Guyana</option>\r\n");
      out.write("                                                    <option value=\"HT\">Haiti</option>\r\n");
      out.write("                                                    <option value=\"HM\">Heard Island and McDonald Islands</option>\r\n");
      out.write("                                                    <option value=\"HN\">Honduras</option>\r\n");
      out.write("                                                    <option value=\"HK\">Hong Kong</option>\r\n");
      out.write("                                                    <option value=\"HU\">Hungary</option>\r\n");
      out.write("                                                    <option value=\"IS\">Iceland</option>\r\n");
      out.write("                                                    <option selected=\"selected\" value=\"IN\">India</option>\r\n");
      out.write("                                                    <option value=\"ID\">Indonesia</option>\r\n");
      out.write("                                                    <option value=\"IR\">Iran</option>\r\n");
      out.write("                                                    <option value=\"IQ\">Iraq</option>\r\n");
      out.write("                                                    <option value=\"IM\">Isle of Man</option>\r\n");
      out.write("                                                    <option value=\"IL\">Israel</option>\r\n");
      out.write("                                                    <option value=\"IT\">Italy</option>\r\n");
      out.write("                                                    <option value=\"CI\">Ivory Coast</option>\r\n");
      out.write("                                                    <option value=\"JM\">Jamaica</option>\r\n");
      out.write("                                                    <option value=\"JP\">Japan</option>\r\n");
      out.write("                                                    <option value=\"JE\">Jersey</option>\r\n");
      out.write("                                                    <option value=\"JO\">Jordan</option>\r\n");
      out.write("                                                    <option value=\"KZ\">Kazakhstan</option>\r\n");
      out.write("                                                    <option value=\"KE\">Kenya</option>\r\n");
      out.write("                                                    <option value=\"KI\">Kiribati</option>\r\n");
      out.write("                                                    <option value=\"KW\">Kuwait</option>\r\n");
      out.write("                                                    <option value=\"KG\">Kyrgyzstan</option>\r\n");
      out.write("                                                    <option value=\"LA\">Laos</option>\r\n");
      out.write("                                                    <option value=\"LV\">Latvia</option>\r\n");
      out.write("                                                    <option value=\"LB\">Lebanon</option>\r\n");
      out.write("                                                    <option value=\"LS\">Lesotho</option>\r\n");
      out.write("                                                    <option value=\"LR\">Liberia</option>\r\n");
      out.write("                                                    <option value=\"LY\">Libya</option>\r\n");
      out.write("                                                    <option value=\"LI\">Liechtenstein</option>\r\n");
      out.write("                                                    <option value=\"LT\">Lithuania</option>\r\n");
      out.write("                                                    <option value=\"LU\">Luxembourg</option>\r\n");
      out.write("                                                    <option value=\"MO\">Macao S.A.R., China</option>\r\n");
      out.write("                                                    <option value=\"MK\">Macedonia</option>\r\n");
      out.write("                                                    <option value=\"MG\">Madagascar</option>\r\n");
      out.write("                                                    <option value=\"MW\">Malawi</option>\r\n");
      out.write("                                                    <option value=\"MY\">Malaysia</option>\r\n");
      out.write("                                                    <option value=\"MV\">Maldives</option>\r\n");
      out.write("                                                    <option value=\"ML\">Mali</option>\r\n");
      out.write("                                                    <option value=\"MT\">Malta</option>\r\n");
      out.write("                                                    <option value=\"MH\">Marshall Islands</option>\r\n");
      out.write("                                                    <option value=\"MQ\">Martinique</option>\r\n");
      out.write("                                                    <option value=\"MR\">Mauritania</option>\r\n");
      out.write("                                                    <option value=\"MU\">Mauritius</option>\r\n");
      out.write("                                                    <option value=\"YT\">Mayotte</option>\r\n");
      out.write("                                                    <option value=\"MX\">Mexico</option>\r\n");
      out.write("                                                    <option value=\"FM\">Micronesia</option>\r\n");
      out.write("                                                    <option value=\"MD\">Moldova</option>\r\n");
      out.write("                                                    <option value=\"MC\">Monaco</option>\r\n");
      out.write("                                                    <option value=\"MN\">Mongolia</option>\r\n");
      out.write("                                                    <option value=\"ME\">Montenegro</option>\r\n");
      out.write("                                                    <option value=\"MS\">Montserrat</option>\r\n");
      out.write("                                                    <option value=\"MA\">Morocco</option>\r\n");
      out.write("                                                    <option value=\"MZ\">Mozambique</option>\r\n");
      out.write("                                                    <option value=\"MM\">Myanmar</option>\r\n");
      out.write("                                                    <option value=\"NA\">Namibia</option>\r\n");
      out.write("                                                    <option value=\"NR\">Nauru</option>\r\n");
      out.write("                                                    <option value=\"NP\">Nepal</option>\r\n");
      out.write("                                                    <option value=\"NL\">Netherlands</option>\r\n");
      out.write("                                                    <option value=\"AN\">Netherlands Antilles</option>\r\n");
      out.write("                                                    <option value=\"NC\">New Caledonia</option>\r\n");
      out.write("                                                    <option value=\"NZ\">New Zealand</option>\r\n");
      out.write("                                                    <option value=\"NI\">Nicaragua</option>\r\n");
      out.write("                                                    <option value=\"NE\">Niger</option>\r\n");
      out.write("                                                    <option value=\"NG\">Nigeria</option>\r\n");
      out.write("                                                    <option value=\"NU\">Niue</option>\r\n");
      out.write("                                                    <option value=\"NF\">Norfolk Island</option>\r\n");
      out.write("                                                    <option value=\"KP\">North Korea</option>\r\n");
      out.write("                                                    <option value=\"NO\">Norway</option>\r\n");
      out.write("                                                    <option value=\"OM\">Oman</option>\r\n");
      out.write("                                                    <option value=\"PK\">Pakistan</option>\r\n");
      out.write("                                                    <option value=\"PS\">Palestinian Territory</option>\r\n");
      out.write("                                                    <option value=\"PA\">Panama</option>\r\n");
      out.write("                                                    <option value=\"PG\">Papua New Guinea</option>\r\n");
      out.write("                                                    <option value=\"PY\">Paraguay</option>\r\n");
      out.write("                                                    <option value=\"PE\">Peru</option>\r\n");
      out.write("                                                    <option value=\"PH\">Philippines</option>\r\n");
      out.write("                                                    <option value=\"PN\">Pitcairn</option>\r\n");
      out.write("                                                    <option value=\"PL\">Poland</option>\r\n");
      out.write("                                                    <option value=\"PT\">Portugal</option>\r\n");
      out.write("                                                    <option value=\"QA\">Qatar</option>\r\n");
      out.write("                                                    <option value=\"IE\">Republic of Ireland</option>\r\n");
      out.write("                                                    <option value=\"RE\">Reunion</option>\r\n");
      out.write("                                                    <option value=\"RO\">Romania</option>\r\n");
      out.write("                                                    <option value=\"RU\">Russia</option>\r\n");
      out.write("                                                    <option value=\"RW\">Rwanda</option>\r\n");
      out.write("                                                    <option value=\"ST\">São Tomé and Príncipe</option>\r\n");
      out.write("                                                    <option value=\"BL\">Saint Barthélemy</option>\r\n");
      out.write("                                                    <option value=\"SH\">Saint Helena</option>\r\n");
      out.write("                                                    <option value=\"KN\">Saint Kitts and Nevis</option>\r\n");
      out.write("                                                    <option value=\"LC\">Saint Lucia</option>\r\n");
      out.write("                                                    <option value=\"SX\">Saint Martin (Dutch part)</option>\r\n");
      out.write("                                                    <option value=\"MF\">Saint Martin (French part)</option>\r\n");
      out.write("                                                    <option value=\"PM\">Saint Pierre and Miquelon</option>\r\n");
      out.write("                                                    <option value=\"VC\">Saint Vincent and the Grenadines</option>\r\n");
      out.write("                                                    <option value=\"SM\">San Marino</option>\r\n");
      out.write("                                                    <option value=\"SA\">Saudi Arabia</option>\r\n");
      out.write("                                                    <option value=\"SN\">Senegal</option>\r\n");
      out.write("                                                    <option value=\"RS\">Serbia</option>\r\n");
      out.write("                                                    <option value=\"SC\">Seychelles</option>\r\n");
      out.write("                                                    <option value=\"SL\">Sierra Leone</option>\r\n");
      out.write("                                                    <option value=\"SG\">Singapore</option>\r\n");
      out.write("                                                    <option value=\"SK\">Slovakia</option>\r\n");
      out.write("                                                    <option value=\"SI\">Slovenia</option>\r\n");
      out.write("                                                    <option value=\"SB\">Solomon Islands</option>\r\n");
      out.write("                                                    <option value=\"SO\">Somalia</option>\r\n");
      out.write("                                                    <option value=\"ZA\">South Africa</option>\r\n");
      out.write("                                                    <option value=\"GS\">South Georgia/Sandwich Islands</option>\r\n");
      out.write("                                                    <option value=\"KR\">South Korea</option>\r\n");
      out.write("                                                    <option value=\"SS\">South Sudan</option>\r\n");
      out.write("                                                    <option value=\"ES\">Spain</option>\r\n");
      out.write("                                                    <option value=\"LK\">Sri Lanka</option>\r\n");
      out.write("                                                    <option value=\"SD\">Sudan</option>\r\n");
      out.write("                                                    <option value=\"SR\">Suriname</option>\r\n");
      out.write("                                                    <option value=\"SJ\">Svalbard and Jan Mayen</option>\r\n");
      out.write("                                                    <option value=\"SZ\">Swaziland</option>\r\n");
      out.write("                                                    <option value=\"SE\">Sweden</option>\r\n");
      out.write("                                                    <option value=\"CH\">Switzerland</option>\r\n");
      out.write("                                                    <option value=\"SY\">Syria</option>\r\n");
      out.write("                                                    <option value=\"TW\">Taiwan</option>\r\n");
      out.write("                                                    <option value=\"TJ\">Tajikistan</option>\r\n");
      out.write("                                                    <option value=\"TZ\">Tanzania</option>\r\n");
      out.write("                                                    <option value=\"TH\">Thailand</option>\r\n");
      out.write("                                                    <option value=\"TL\">Timor-Leste</option>\r\n");
      out.write("                                                    <option value=\"TG\">Togo</option>\r\n");
      out.write("                                                    <option value=\"TK\">Tokelau</option>\r\n");
      out.write("                                                    <option value=\"TO\">Tonga</option>\r\n");
      out.write("                                                    <option value=\"TT\">Trinidad and Tobago</option>\r\n");
      out.write("                                                    <option value=\"TN\">Tunisia</option>\r\n");
      out.write("                                                    <option value=\"TR\">Turkey</option>\r\n");
      out.write("                                                    <option value=\"TM\">Turkmenistan</option>\r\n");
      out.write("                                                    <option value=\"TC\">Turks and Caicos Islands</option>\r\n");
      out.write("                                                    <option value=\"TV\">Tuvalu</option>\r\n");
      out.write("                                                    <option value=\"UG\">Uganda</option>\r\n");
      out.write("                                                    <option value=\"UA\">Ukraine</option>\r\n");
      out.write("                                                    <option value=\"AE\">United Arab Emirates</option>\r\n");
      out.write("                                                    <option value=\"GB\">United Kingdom (UK)</option>\r\n");
      out.write("                                                    <option value=\"US\">United States (US)</option>\r\n");
      out.write("                                                    <option value=\"UY\">Uruguay</option>\r\n");
      out.write("                                                    <option value=\"UZ\">Uzbekistan</option>\r\n");
      out.write("                                                    <option value=\"VU\">Vanuatu</option>\r\n");
      out.write("                                                    <option value=\"VA\">Vatican</option>\r\n");
      out.write("                                                    <option value=\"VE\">Venezuela</option>\r\n");
      out.write("                                                    <option value=\"VN\">Vietnam</option>\r\n");
      out.write("                                                    <option value=\"WF\">Wallis and Futuna</option>\r\n");
      out.write("                                                    <option value=\"EH\">Western Sahara</option>\r\n");
      out.write("                                                    <option value=\"WS\">Western Samoa</option>\r\n");
      out.write("                                                    <option value=\"YE\">Yemen</option>\r\n");
      out.write("                                                    <option value=\"ZM\">Zambia</option>\r\n");
      out.write("                                                    <option value=\"ZW\">Zimbabwe</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"lastname\">Name</label>\r\n");
      out.write("                                                <input type=\"text\" value=\"\" class=\"form-control\"  required=\"required\" placeholder=\"\" id=\"billing_first_name\" name=\"name\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"company\">Address</label>\r\n");
      out.write("                                            <textarea rows=\"4\" required=\"required\" cols=\"50\" value=\"\" placeholder=\"Street address\" id=\"billing_address_1\" name=\"address\" class=\"form-control\"></textarea>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"street\">Town / City</label>\r\n");
      out.write("                                          <input type=\"text\" value=\"\" required=\"required\" placeholder=\"Town / City\" id=\"billing_city\" name=\"city\" class=\"form-control\">\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"company\">Postcode</label>\r\n");
      out.write("                                                <input type=\"text\" required=\"required\" runat=\"server\" onkeypress=\"javascript:return isNumber1(event)\" value=\"\" placeholder=\"Postcode / Zip\" id=\"billing_postcode\" name=\"pin\" required=\"required\" class=\"form-control\">\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"street\">Email</label>\r\n");
      out.write("                                                <input type=\"email\" required=\"required\" value=\"");
      out.print(email );
      out.write("\" placeholder=\"\" id=\"billing_email\" name=\"email\" class=\"form-control\">\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"company\">Telephone</label>\r\n");
      out.write("                                           <input type=\"text\" required=\"required\" ID=\"tbNumbers\"  runat=\"server\" \r\n");
      out.write("            onkeypress=\"javascript:return isNumber(event)\"  placeholder=\"\"  name=\"phone\" class=\"form-control\">\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                   \r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                              \r\n");
      out.write("                                <!-- /.row -->\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"box-footer\">\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"pull-right\">\r\n");
      out.write("                                    <button type=\"submit\"  onclick=\"return ValidateNo();\" class=\"btn btn-primary\">Continue to Delivery Method<i class=\"fa fa-chevron-right\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.box -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\t");

	
	
}



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- /.col-md-9 -->\r\n");

                                    int i = 0;
                                    String pr="";
                                    int prc=0;
                                    int sum=0;
                                    
                                    Double dis=0.0;
                                    int idis=0;
                                    String af="";
	                                    PreparedStatement ps = con.prepareStatement("SELECT cart.qty,cart.subtotal, cart.total, cart.shippingcharges,product.price, cart.productid,product.p_type,product.mrp, product.title,product.discount, product.imageUrlStr FROM cart,product WHERE cart.productid = product.productId and cart.userid = " + userid + "");
	                                    ResultSet rs = ps.executeQuery();
	                                    while(rs.next())
	                                    {
	                                    	idis=rs.getInt("discount");
	                            			af=dis.toString();
	                                    pr=rs.getString("total");
	                                    prc=Integer.parseInt(pr);

	                                    sum=sum+prc;
	                                    System.out.println(sum);

	                                    }
	                                    
                                    
      out.write("\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"box\" id=\"order-summary\">\r\n");
      out.write("                        <div class=\"box-header\">\r\n");
      out.write("                            <h3>Order summary</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-muted\">Shipping and additional costs are calculated based on the values you have entered.</p>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <table class=\"table\">\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>Order subtotal</td>\r\n");
      out.write("                                        <th>&#8377;");
      out.print(sum );
      out.write("</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>Shipping and handling</td>\r\n");
      out.write("                                        <th>0</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>Tax</td>\r\n");
      out.write("                                        <th>0.00</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr class=\"total\">\r\n");
      out.write("                                        <td>Total</td>\r\n");
      out.write("                                        <th>&#8377;");
      out.print(sum );
      out.write("</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#content -->\r\n");
      out.write("\r\n");
      out.write("        <!-- *** FOOTER ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("         <div id=\"footer\" data-animate=\"fadeInUp\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                       \r\n");
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("\t\r\n");
      out.write("                       \r\n");
      out.write("\r\n");
      out.write("                        <h4>User section</h4>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                        <ul>\r\n");
      out.write("                        ");

				if(userid>=1){
					
					 
      out.write("\r\n");
      out.write("\t\t\t\t\t <li ><a  href=\"logout.jsp\"><i class=\"fa fa-user\"></i>Logout </a>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t ");

				}
				else{
					
					
      out.write("\r\n");
      out.write("\t\t\t\t\t  <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\">Login</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"register.jsp\">Regiter</a>\r\n");
      out.write("                            </li> \r\n");
      out.write("\t\t\t\t\t");

				}
				
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"hidden-md hidden-lg hidden-sm\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("                        <h4>Top categories</h4>\r\n");
      out.write("\r\n");
      out.write("                        <h5>Electronic</h5>\r\n");
      out.write("\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li ><a href=\"shop.jsp?p_type=1&brand=mobile\">Mobile</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=4&brand=Laptop\">Laptop</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=2&brand=Headphone\">Headphone</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=3&brand=Speaker\">Speaker</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li ><a href=\"shop.jsp?p_type=5&brand=Printer\">Printer</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"hidden-md hidden-lg\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("\r\n");
      out.write("                        <a href=\"contact.html\">Go to contact page</a>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"hidden-md hidden-lg\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#footer -->\r\n");
      out.write("\r\n");
      out.write("        <!-- *** FOOTER END *** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- *** COPYRIGHT ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- *** COPYRIGHT END *** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#all -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- *** SCRIPTS TO INCLUDE ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("    <script src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.cookie.js\"></script>\r\n");
      out.write("    <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"js/modernizr.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap-hover-dropdown.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/front.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
